language: node_js
node_js:
- '7'
- '6'
- '4'
deploy:
  api_key:
    secure: sg4ngTmLGfE7YA46aFkiyYo2TwJuaeQolIFFBKSQtyV2KKo6y1S0Dau9YmqCrcwddqy4abyQD8dV5C1sqSWJHCNS2NTr2t/P5D0fNTOHuqJoKEgXpxXvcpDsoUzdip5B9QpNF94TEN4zaD/uxHazjDmqM1s2GmYO84VR5RxBuHAbjTFSzQPYf+TPXGNYjG9epVryiKKkRgWSBBtY1U+9V7wJw0xjpKRjyjsDTlbnCFqaLZd9LxmXUVgS2hTt8DdUi6T01BOZdrjav4nMr1ZWI1yLv35HReyY6EVusQszfo3CcDy/ZEdp9lCUY/cuh0Oj7U+Xp9Zjgwi83Mj8z2gq308jIIDo/SpKsXGdczC29TvxrlJjr/Kg5tjGtnA/FYSmpy7WR2D0Rgd5qNhxOsUfE3lmIj3Cb64bOdjY8e9cgFbrStE2cWmLXA5ARwOEz0Zh5bhhOlOvwTwxIH+Eua5eY2z7nyXTo3uPC/BsssvE5KL/yiPGqdAShZytp1PLSVLMiF1CjApE2+zX+sH8msXcwvRcEkpURlgrUSd6lHKt7pIe8hMD0Zm2uaQDHAqdhsmFy85s/g6zKrpilUe3VFbqfjT3Mok8+vyyDMVDphgD49Xh/rbHOot6lJsV7n1Dtt1erfVdyzCQKXRlzl9imhqUdHWG9gmUTMd1sGOejfhzy1I=
  email: julian@dotcore.co.il
  provider: npm
  on:
    tags: true
script: npm run lint && npm run build
